
- name: MasterNode### Uprage cache 
  yum: name=* state=latest

- name: MasterNode### Install packages On master node
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - httpd
    - php
    - php-gd
    - php-pear
    - php-intl
    - php-soap
    - php.x86_64
    - perl-DBD-MySQL
    - MySQL-python
    - php-intl
    - php-ldap
    - php-mysql
    - php-soap
    - php-xml
    - mod_ssl
    - php-process
    - bind.x86_64
    - bind-chroot
    - firewalld
    - namedmanager-www
    - namedmanager-bind
    - vim
    - bind-utils

- name: MasterNode### setup-named-chroot
  command: "/usr/libexec/setup-named-chroot.sh /var/named/chroot on"

- name: MasterNode### copy named.conf file in /var/named/chroot/etc/
  file: src=named.conf dest=/var/named/chroot/etc/named.conf owner=root group=named mode=644 state=touch

- name: MasterNode### create named.namedmanager.conf file in /var/named/chroot/etc/
  file: path=/var/named/chroot/etc/named.namedmanager.conf state=touch owner=named group=named mode=644
  
- name: MasterNode### touch file namedmanager_messages
  file: path=/var/log/namedmanager_messages state=touch group=named

- name: MasterNode### Start and Enable Service httpd and Mysql
  service: name={{ item }} state=started enabled=yes
  with_items:
    - httpd
    - mysqld
    - firewalld

- name: MasterNode### add servername in httpd.conf
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp=^#ServerName line="ServerName {{ ansible_fqdn }}:80"

- name: MasterNode### MySQL firewalld rules
  firewalld:
    port={{ item }}
    permanent=true
    state=enabled
    immediate=true
  with_items:
    - "{{ dns }}/tcp"
    - "{{ dns }}/udp"
    - "{{ http }}/tcp"
    - "{{ https }}/tcp"

- name: MasterNode### Set root password for localhost
  mysql_user:
    name=root
    password={{ mariadb_root_password }}
    host=localhost
    state=present

- name: MasterNode### Creating the /root/.my.cnf file
  template:
    src=my.cnf.j2
    dest=/root/.my.cnf
    mode=0640

- name: MasterNode### add conf-bind.php file
  template: src=config-bind.php.j2 dest=/etc/namedmanager/config-bind.php group=root owner=root mode=0644

- name: MasterNode### add namedmanager.conf file
  template: src=namedmanager.conf.j2 dest=/etc/httpd/conf.d/namedmanager.conf group=root owner=root mode=0644

- name: MasterNode### add autoinstall file
  template: src=autoinstall.pl.j2 dest=/usr/share/namedmanager/resources/autoinstall.pl group=root owner=root mode=0755

- name: MasterNode### bd installation
  command: /usr/share/namedmanager/resources/autoinstall.pl

- name: MasterNode### Start and Enable Service httpd and Mysql
  service: name=mysqld state=restarted

- name: MasterNode### enable and Enable Service named-chroot
  service: name=named-chroot state=started enabled=yes


- name: MasterNode### reStart httpd Service
  service: name=httpd state=restarted

- name: Othernode### Start and Enable Service namedmanager_logpush
  service: name=namedmanager_logpush state=started enabled=yes