
- name: Othernode### Uprage cache 
  yum: name=* state=latest

- name: Othernode### Install packages On others nodes
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - firewalld
    - namedmanager-bind
    - bind-chroot
    - vim
    - bind-utils
 
- name: Othernode### setup-named-chroot
  command: "/usr/libexec/setup-named-chroot.sh /var/named/chroot on"
  
- name: Othernode### copy named.conf file in /var/named/chroot/etc/
  file: src=named.conf dest=/var/named/chroot/etc/named.conf owner=root group=named mode=644 state=touch

- name: Othernode### create named.namedmanager.conf file in /var/named/chroot/etc/
  file: path=/var/named/chroot/etc/named.namedmanager.conf state=touch owner=named group=named mode=644

- name: Othernode### touch file namedmanager_messages in /var/log
  file: path=/var/log/namedmanager_messages state=touch group=named


- name: Othernode### Start and Enable Service firewalld
  service: name={{ item }} state=started enabled=yes
  with_items:
    - firewalld

- name: Othernode### firewalld rules
  firewalld:
    port={{ item }}
    permanent=true
    state=enabled
    immediate=true
  with_items:
    - "{{ dns }}/tcp"
    - "{{ dns }}/udp"

- name: Othernode### add config-bind.php file
  template: src=config-bind.php.j2 dest=/etc/namedmanager/config-bind.php group=root owner=root mode=0644
  

- name: Othernode### Start and Enable Service named-chroot
  service: name=named-chroot state=started enabled=yes

- name: Othernode### Start and Enable Service namedmanager_logpush
  service: name=namedmanager_logpush state=started enabled=yes